name: Python CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o repositório
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2'

      - name: Instalar Pipenv
        run: |
          python -m pip install pipenv

      - name: Instalar dependências
        run: |
          pipenv install --dev

      - name: Rodar testes
        run: |
          pipenv run pytest
